name: MacOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        brew install boost@1.74 htslib
        export CXXFLAGS='-I/opt/homebrew/opt/boost@1.74/include -I/opt/homebrew/opt/htslib/include'
        export LDFLAGS='-L/opt/homebrew/opt/boost@1.74/lib -L/opt/homebrew/opt/htslib/lib'
        make
