name: MacOS-15 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        brew install autoconf automake boost htslib llvm libomp
        make
